## Дополнительные задания*

### Задание 1 

Загрузите датасет **Wine** из встроенных датасетов **sklearn.datasets** с помощью функции **load_wine** в переменную **data**.

In [1]:
from sklearn.datasets import load_wine

data = load_wine()

### Задание 2

Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список **data_keys**, содержащий её ключи.

In [2]:
print(type(data))

<class 'sklearn.utils.Bunch'>


In [3]:
data_keys = data.keys()
data_keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

### Задание 3

Просмотрите данные, описание и названия признаков в датасете. Описание нужно вывести в виде привычного, аккуратно оформленного текста, без обозначений переноса строки, но с самими переносами и т.д.

In [4]:
print(data.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [5]:
print(data.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [6]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

### Задание 4

Сколько классов содержит целевая переменная датасета? Выведите названия классов.

In [7]:
print('Количество классов целевой переменной:', data.target_names.size)
print('Названия классов целевой переменной:', data.target_names)

Количество классов целевой переменной: 3
Названия классов целевой переменной: ['class_0' 'class_1' 'class_2']


### Задание 5

На основе данных датасета (они содержатся в двумерном массиве **Numpy**) и названий признаков создайте датафрейм под названием _**X**_.

In [8]:
import pandas as pd
import numpy as np

X = pd.DataFrame(data['data'], columns = data['feature_names'])
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

### Задание 6

Выясните размер датафрейма **X** и установите, имеются ли в нём пропущенные значения.

In [9]:
print('Форма датафрейма X:', X.shape)
print('Размерность датафрейма X:', X.ndim)
print('Количество элементов датафрейма X:', X.size)

Форма датафрейма X: (178, 13)
Размерность датафрейма X: 2
Количество элементов датафрейма X: 2314


In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

### Задание 7

Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных **numpy.int64**. Название поля - '**target**'.

In [11]:
X['target'] = data['target'].astype(np.int64)
print('Форма датафрейма X:', X.shape)
print('Размерность датафрейма X:', X.ndim)
print('Количество элементов датафрейма X:', X.size)

Форма датафрейма X: (178, 14)
Размерность датафрейма X: 2
Количество элементов датафрейма X: 2492


In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  targe

### Задание 8

Постройте матрицу корреляций для всех полей **X**. Дайте полученному датафрейму название **X_corr**.

In [13]:
X_corr = X.corr().round(3)
X_corr

alcohol  malic_acid    ash  alcalinity_of_ash  \
alcohol                         1.000       0.094  0.212             -0.310   
malic_acid                      0.094       1.000  0.164              0.289   
ash                             0.212       0.164  1.000              0.443   
alcalinity_of_ash              -0.310       0.289  0.443              1.000   
magnesium                       0.271      -0.055  0.287             -0.083   
total_phenols                   0.289      -0.335  0.129             -0.321   
flavanoids                      0.237      -0.411  0.115             -0.351   
nonflavanoid_phenols           -0.156       0.293  0.186              0.362   
proanthocyanins                 0.137      -0.221  0.010             -0.197   
color_intensity                 0.546       0.249  0.259              0.019   
hue                            -0.072      -0.561 -0.075             -0.274   
od280/od315_of_diluted_wines    0.072      -0.369  0.004             -0.277   
proline                         0.644      -0.192  0.224             -0.441   
target                         -0.328       0.438 -0.050              0.518   

                              magnesium  total_phenols  flavanoids  \
alcohol                           0.271          0.289       0.237   
malic_acid                       -0.055         -0.335      -0.411   
ash                               0.287          0.129       0.115   
alcalinity_of_ash                -0.083         -0.321      -0.351   
magnesium                         1.000          0.214       0.196   
total_phenols                     0.214          1.000       0.865   
flavanoids                        0.196          0.865       1.000   
nonflavanoid_phenols             -0.256         -0.450      -0.538   
proanthocyanins                   0.236          0.612       0.653   
color_intensity                   0.200         -0.055      -0.172   
hue                               0.055          0.434       0.543   
od280/od315_of_diluted_wines      0.066          0.700       0.787   
proline                           0.393          0.498       0.494   
target                           -0.209         -0.719      -0.847   

                              nonflavanoid_phenols  proanthocyanins  \
alcohol                                     -0.156            0.137   
malic_acid                                   0.293           -0.221   
ash                                          0.186            0.010   
alcalinity_of_ash                            0.362           -0.197   
magnesium                                   -0.256            0.236   
total_phenols                               -0.450            0.612   
flavanoids                                  -0.538            0.653   
nonflavanoid_phenols                         1.000           -0.366   
proanthocyanins                             -0.366            1.000   
color_intensity                              0.139           -0.025   
hue                                         -0.263            0.296   
od280/od315_of_diluted_wines                -0.503            0.519   
proline                                     -0.311            0.330   
target                                       0.489           -0.499   

                              color_intensity    hue  \
alcohol                                 0.546 -0.072   
malic_acid                              0.249 -0.561   
ash                                     0.259 -0.075   
alcalinity_of_ash                       0.019 -0.274   
magnesium                               0.200  0.055   
total_phenols                          -0.055  0.434   
flavanoids                             -0.172  0.543   
nonflavanoid_phenols                    0.139 -0.263   
proanthocyanins                        -0.025  0.296   
color_intensity                         1.000 -0.522   
hue                                    -0.522  1.000   
od280/od315_of_diluted_wines           -0.429  0.565   

### Задание 9

Создайте список **high_corr** из признаков, корреляция которых с полем **target** по абсолютному значению превышает 0.5 (причём, само поле **target** не должно входить в этот список).

In [14]:
high_corr = list(X_corr.columns[(abs(X_corr['target']) > 0.5) & (X_corr.columns != 'target')])
high_corr

['alcalinity_of_ash',
 'total_phenols',
 'flavanoids',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [15]:
high_corr2 = X_corr.abs().target.sort_values(ascending = False)
high_corr2 = (high_corr2[(high_corr2 > 0.5) & (high_corr2 != 1.000)])
high_corr2

flavanoids                      0.847
od280/od315_of_diluted_wines    0.788
total_phenols                   0.719
proline                         0.634
hue                             0.617
alcalinity_of_ash               0.518
Name: target, dtype: float64

### Задание 10

Удалите из датафрейма **X** поле с целевой переменной. Для всех признаков, названия которых содержатся в списке **high_corr**, вычислите квадрат их значений и добавьте в датафрейм **X** соответствующие поля с суффиксом '**_2**', добавленного к первоначальному названию признака. Итоговый датафрейм должен содержать все поля, которые, были в нём изначально, а также поля с признаками из списка **high_corr**, возведёнными в квадрат. Выведите описание полей датафрейма **X** с помощью метода **describe**.

In [16]:
X.drop('target', axis=1, inplace=True)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [17]:
for feature_name in high_corr:
    X[f'{feature_name}_2'] = X.apply(lambda row: row[feature_name] ** 2, axis = 1)

X.describe().T.round(3)

count        mean         std        min  \
alcohol                         178.0      13.001       0.812     11.030   
malic_acid                      178.0       2.336       1.117      0.740   
ash                             178.0       2.367       0.274      1.360   
alcalinity_of_ash               178.0      19.495       3.340     10.600   
magnesium                       178.0      99.742      14.282     70.000   
total_phenols                   178.0       2.295       0.626      0.980   
flavanoids                      178.0       2.029       0.999      0.340   
nonflavanoid_phenols            178.0       0.362       0.124      0.130   
proanthocyanins                 178.0       1.591       0.572      0.410   
color_intensity                 178.0       5.058       2.318      1.280   
hue                             178.0       0.957       0.229      0.480   
od280/od315_of_diluted_wines    178.0       2.612       0.710      1.270   
proline                         178.0     746.893     314.907    278.000   
alcalinity_of_ash_2             178.0     391.143     133.672    112.360   
total_phenols_2                 178.0       5.657       2.936      0.960   
flavanoids_2                    178.0       5.110       4.211      0.116   
hue_2                           178.0       0.969       0.444      0.230   
od280/od315_of_diluted_wines_2  178.0       7.322       3.584      1.613   
proline_2                       178.0  656459.140  555859.140  77284.000   

                                       25%         50%         75%  \
alcohol                             12.362      13.050      13.678   
malic_acid                           1.602       1.865       3.082   
ash                                  2.210       2.360       2.558   
alcalinity_of_ash                   17.200      19.500      21.500   
magnesium                           88.000      98.000     107.000   
total_phenols                        1.742       2.355       2.800   
flavanoids                           1.205       2.135       2.875   
nonflavanoid_phenols                 0.270       0.340       0.438   
proanthocyanins                      1.250       1.555       1.950   
color_intensity                      3.220       4.690       6.200   
hue                                  0.782       0.965       1.120   
od280/od315_of_diluted_wines         1.938       2.780       3.170   
proline                            500.500     673.500     985.000   
alcalinity_of_ash_2                295.840     380.250     462.250   
total_phenols_2                      3.036       5.546       7.840   
flavanoids_2                         1.452       4.558       8.266   
hue_2                                0.612       0.931       1.254   
od280/od315_of_diluted_wines_2       3.754       7.728      10.049   
proline_2                       250501.000  453604.500  970225.000   

                                        max  
alcohol                              14.830  
malic_acid                            5.800  
ash                                   3.230  
alcalinity_of_ash                    30.000  
magnesium                           162.000  
total_phenols                         3.880  
flavanoids                            5.080  
nonflavanoid_phenols                  0.660  
proanthocyanins                       3.580  
color_intensity                      13.000  
hue                                   1.710  
od280/od315_of_diluted_wines          4.000  
proline                            1680.000  
alcalinity_of_ash_2                 900.000  
total_phenols_2                      15.054  
flavanoids_2                         25.806  
hue_2                                 2.924  
od280/od315_of_diluted_wines_2       16.000  
proline_2                       2822400.000

-----
END Части 2