# Задания на повторение материала**

## Задание 1

Создать одномерный массив **Numpy** под названием _**a**_ из 12 последовательных целых чисел от 12 до 24 невключительно.

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
print('Массив a: {}'.format(a))
print('Тип массива a: {}'.format(a.dtype))
print('Форма массива a: {}'.format(a.shape))
print('Размерность массива a: {}'.format(a.ndim))
print('Количество элементов массива a: {}'.format(a.size))

Массив a: [12 13 14 15 16 17 18 19 20 21 22 23]
Тип массива a: int32
Форма массива a: (12,)
Размерность массива a: 1
Количество элементов массива a: 12


## Задание 2

Создать 5 двумерных массивов разной формы из массива _**a**_. Не использовать в аргументах метода **reshape** число -1.

In [3]:
a1 = a.reshape(12, 1)
print('Массив a1:\n', a1)
print('Размерность массива a1: {}'.format(a1.ndim))

Массив a1:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Размерность массива a1: 2


In [4]:
a2 = a.reshape(6, 2)
print('Массив a2:\n', a2)
print('Размерность массива a2: {}'.format(a2.ndim))

Массив a2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Размерность массива a2: 2


In [5]:
a3 = a.reshape(2, 6)
print('Массив a3:\n', a3)
print('Размерность массива a3: {}'.format(a3.ndim))

Массив a3:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Размерность массива a3: 2


In [6]:
a4 = a.reshape(4, 3)
print('Массив a4:\n', a4)
print('Размерность массива a4: {}'.format(a4.ndim))

Массив a4:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Размерность массива a4: 2


In [7]:
a5 = a.reshape(3, 4)
print('Массив a5:\n', a5)
print('Размерность массива a5: {}'.format(a5.ndim))

Массив a5:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Размерность массива a5: 2


## Задание 3

Создать 5 двумерных массивов разной формы из массива _**a**_. Использовать в аргументах метода **reshape** число -1 (в трёх примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a6 = a.reshape(12, -1)
print('Массив a6:\n', a6)
print('Размерность массива a6: {}'.format(a6.ndim))

Массив a6:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Размерность массива a6: 2


In [9]:
a7 = a.reshape(6, -1)
print('Массив a7:\n', a7)
print('Размерность массива a7: {}'.format(a7.ndim))

Массив a7:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Размерность массива a7: 2


In [10]:
a8 = a.reshape(4, -1)
print('Массив a8:\n', a8)
print('Размерность массива a8: {}'.format(a8.ndim))

Массив a8:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Размерность массива a8: 2


In [11]:
a9 = a.reshape(-1, 6)
print('Массив a9:\n', a9)
print('Размерность массива a9: {}'.format(a9.ndim))

Массив a9:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Размерность массива a9: 2


In [12]:
a10 = a.reshape(-1, 4)
print('Массив a10:\n', a10)
print('Размерность массива a10: {}'.format(a10.ndim))

Массив a10:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Размерность массива a10: 2


## Задание 4

Можно ли массив **Numpy**, состоящий из одного столбца и 12 строк, назвать одномерным?

### Ответ:

Нет, нельзя. Достаточно взлянуть на размерность (она равна 2) исследуемого массива в ответах на Задания 2 и 3 (массивы _**a1**_ и _**a6**_ соответственно).

## Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом **size**, как и исходный массив.

In [13]:
x = np.random.randn(3, 4)
print('Массив x:\n', x)
print('Размерность массива x: {}'.format(x.ndim))
print('Количество элементов массива x: {}'.format(x.size))
print('Среднее значение массива x: {}'.format(x.mean()))
print('Среднее квадратическое отклонение массива x: {}'.format(x.std()))

Массив x:
 [[ 0.90008514  0.15158786 -1.94841386  2.19494632]
 [-1.24217867  0.69675146 -0.59023062  0.48890217]
 [ 0.10037714  0.54809587 -0.33723802  3.3259297 ]]
Размерность массива x: 2
Количество элементов массива x: 12
Среднее значение массива x: 0.3573845397594239
Среднее квадратическое отклонение массива x: 1.3545123347954418


In [14]:
x1 = x.flatten()
print('Массив x1:\n', x1)
print('Размерность массива x1: {}'.format(x1.ndim))
print('Количество элементов массива x1: {}'.format(x1.size))
print('Среднее значение массива x1: {}'.format(x1.mean()))
print('Среднее квадратическое отклонение массива x1: {}'.format(x1.std()))

Массив x1:
 [ 0.90008514  0.15158786 -1.94841386  2.19494632 -1.24217867  0.69675146
 -0.59023062  0.48890217  0.10037714  0.54809587 -0.33723802  3.3259297 ]
Размерность массива x1: 1
Количество элементов массива x1: 12
Среднее значение массива x1: 0.3573845397594239
Среднее квадратическое отклонение массива x1: 1.3545123347954418


## Задание 6

Создать массив _**a**_, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [15]:
a = np.arange(20, 0, -2)
print('Массив a: {}'.format(a))
print('Тип массива a: {}'.format(a.dtype))
print('Форма массива a: {}'.format(a.shape))
print('Размерность массива a: {}'.format(a.ndim))
print('Количество элементов массива a: {}'.format(a.size))

Массив a: [20 18 16 14 12 10  8  6  4  2]
Тип массива a: int32
Форма массива a: (10,)
Размерность массива a: 1
Количество элементов массива a: 10


## Задание 7

Создать массив _**b**_, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.

В чём разница между массивами _**a**_ и _**b**_?

In [16]:
b = np.arange(20, 1, -2)
print('Массив b: {}'.format(b))
print('Тип массива b: {}'.format(b.dtype))
print('Форма массива b: {}'.format(b.shape))
print('Размерность массива b: {}'.format(b.ndim))
print('Количество элементов массива b: {}'.format(b.size))

Массив b: [20 18 16 14 12 10  8  6  4  2]
Тип массива b: int32
Форма массива b: (10,)
Размерность массива b: 1
Количество элементов массива b: 10


### Ответ:

Исследование массивов _**a**_ и _**b**_ (из Заданий 6 и 7) показало, что разница в результатах отсутствует по причине заданного интервала между элементами этих массивов, равного 2. Таким образом, единственная разница исследуемых массивов заключена в самом условии, а именно в заданных пределах правых границ массивов (0 и 1 соответственно).

## Задание 8

Вертикально соединить массивы _**a**_ и _**b**_. _**a**_ - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива _**b**_, состоящего из единиц. Итоговый массив _**v**_ должен иметь атрибут **size**, равный 10.

In [17]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print('Массив v:\n', v)
print('Количество элементов массива v: {}'.format(v.size))

Массив v:
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Количество элементов массива v: 10


## Задание 9

Создать одномерный массив _**а**_, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица _**A**_ (двумерный массив **Numpy**), состоящая из 4 строк и 3 столбцов. Получить матрицу _**At**_ путём транспонирования матрицы _**A**_. Получить матрицу _**B**_, умножив матрицу _**A**_ на матрицу _**At**_ с помощью матричного умножения. Какой размер имеет матрица _**B**_?

Получится ли вычислить обратную матрицу для матрицы _**B**_ и почему?

In [18]:
a = np.arange(12, dtype = 'int32')
print('Массив a: {}'.format(a))
print('Форма массива a: {}'.format(a.shape))
print('Размерность массива a: {}'.format(a.ndim))
print('Количество элементов массива a: {}'.format(a.size))

Массив a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Форма массива a: (12,)
Размерность массива a: 1
Количество элементов массива a: 12


In [19]:
A = a.reshape(4, 3)
print('Матрица A:\n', A)
print('Форма матрицы A: {}'.format(A.shape))
print('Размерность матрицы A: {}'.format(A.ndim))
print('Количество элементов матрицы A: {}'.format(A.size))

Матрица A:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Форма матрицы A: (4, 3)
Размерность матрицы A: 2
Количество элементов матрицы A: 12


In [20]:
At = A.T
print('Транспонированная матрица A:\n', At)
print('Форма транспонированной матрицы A: {}'.format(At.shape))
print('Размерность транспонированной матрицы A: {}'.format(At.ndim))
print('Количество элементов транспонированной матрицы A: {}'.format(At.size))

Транспонированная матрица A:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Форма транспонированной матрицы A: (3, 4)
Размерность транспонированной матрицы A: 2
Количество элементов транспонированной матрицы A: 12


In [21]:
B = A.dot(At)
print('Матрица B:\n', B)
print('Форма матрицы B: {}'.format(B.shape))
print('Размер матрицы B: {}'.format(len(B)))
print('Ранг матрицы B: {}'.format(np.linalg.matrix_rank(B)))
print('Определитель матрицы B: {}'.format(np.linalg.det(B)))

Матрица B:
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Форма матрицы B: (4, 4)
Размер матрицы B: 4
Ранг матрицы B: 2
Определитель матрицы B: 0.0


### Ответ:

Вычислить обратную матрицу для квадратной мартицы _**B**_ не получится, в виду нулевого значения её определителя. А если определитель матрицы равен 0, то определитль обратной матрицы равен 1/0 (что недопустимо), именно поэтому матрицы с нулевым определителем обращать нельзя.

Определитель матрицы отличен от 0 тогда и только тогда, когда все строки (вектора) матрицы являются линейно независимыми. Ленейная независимость векторов матрицы определяется равенством её размера и ранга. И так как в нашем случае ранг (2) не равен размеру (4) марицы, мы получили нулевой определитель.

## Задание 10

Инициализируйте генератор случайных чисел с помощью объекта _**seed**_, равного 42.

In [22]:
np.random.seed(42)
print('Генерация псевдослучайного числа относительно предыдущего, равного 42:\n', 
      np.random.random())

Генерация псевдослучайного числа относительно предыдущего, равного 42:
 0.3745401188473625


## Задание 11

Создайте одномерный массив _**c**_, составленный из последовательности 16-ти случайных равномерно распределённых целых чисел от 0 до 16 невключительно.

In [23]:
c = np.random.randint(0, 16, 16)
print('Массив c: {}'.format(c))
print('Тип массива c: {}'.format(c.dtype))
print('Форма массива c: {}'.format(c.shape))
print('Размерность массива c: {}'.format(c.ndim))
print('Количество элементов массива c: {}'.format(c.size))

Массив c: [12 14 10  7 12  4  6  9  2  6 10 10  7  4  3  7]
Тип массива c: int32
Форма массива c: (16,)
Размерность массива c: 1
Количество элементов массива c: 16


## Задание 12

Поменяйте форму массива _**c**_ из Задания 11 так, чтобы получилась квадратная матрица _**C**_. Получите матрицу _**D**_, поэлементно прибавив матрицу _**B**_ из Задания 9 к матрице _**C**_, умноженной на 10. Вычислите определитель, ранг и обратную матрицу **D_inv** для _**D**_.

In [24]:
C = c.reshape(4, 4)
print('Матрица C:\n', C)
print('Тип матрицы C: {}'.format(C.dtype))
print('Форма матрицы C: {}'.format(C.shape))
print('Размерность матрицы C: {}'.format(C.ndim))
print('Количество элементов матрицы C: {}'.format(C.size))

Матрица C:
 [[12 14 10  7]
 [12  4  6  9]
 [ 2  6 10 10]
 [ 7  4  3  7]]
Тип матрицы C: int32
Форма матрицы C: (4, 4)
Размерность матрицы C: 2
Количество элементов матрицы C: 16


In [25]:
D = B + C * 10
print('Матрица D:\n', D)
print('Тип матрицы D: {}'.format(D.dtype))
print('Форма матрицы D: {}'.format(D.shape))
print('Размер матрицы D: {}'.format(len(D)))
print('Ранг матрицы D: {}'.format(np.linalg.matrix_rank(D)))
print('Определитель матрицы D: {}'.format(np.linalg.det(D)))

Матрица D:
 [[125 154 123 102]
 [134  90 146 212]
 [ 43 146 249 312]
 [102 162 242 372]]
Тип матрицы D: int32
Форма матрицы D: (4, 4)
Размер матрицы D: 4
Ранг матрицы D: 4
Определитель матрицы D: -149097600.0


In [26]:
D_inv = np.linalg.inv(D)
print('Обратная матрица D_inv:\n', D_inv)
print('Тип обратной матрицы D_inv: {}'.format(D_inv.dtype))
print('Форма обратной матрицы D_inv: {}'.format(D_inv.shape))
print('Размер матрицы D_inv: {}'.format(len(D_inv)))
print('Ранг матрицы D_inv: {}'.format(np.linalg.matrix_rank(D_inv)))
print('Определитель матрицы D_inv: {}'.format(np.linalg.det(D_inv)))

Обратная матрица D_inv:
 [[ 0.0004711   0.0111539  -0.00253901 -0.00435621]
 [ 0.00957225 -0.01715762 -0.00876527  0.01450486]
 [-0.00167085  0.01408514  0.02130578 -0.02543824]
 [-0.00321078 -0.00474937 -0.0093469   0.01411451]]
Тип обратной матрицы D_inv: float64
Форма обратной матрицы D_inv: (4, 4)
Размер матрицы D_inv: 4
Ранг матрицы D_inv: 4
Определитель матрицы D_inv: -6.707016075376153e-09


Проверка обратной матрицы производится путём умножения  её на исходную матрицу, что в результате должно дать единичную матрицу. Убедимся в этом:

In [27]:
print('Проверочная единичная матрица:\n', D.dot(D_inv))

Проверочная единичная матрица:
 [[ 1.00000000e+00  4.44089210e-16  3.33066907e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00  8.88178420e-16]
 [ 2.22044605e-16  4.44089210e-16  4.44089210e-16  1.00000000e+00]]


## Задание 13

Приравняйте к нулю отрицательные числа в матрице _**D_inv**_ (из Задания 12), а положительные - к единице. Убедитесь, что в матрице _**D_inv_new**_ остались только нули и единицы. С помощью функции **numpy.where**, используя матрицу _**D_inv_new**_ в качестве маски, а матрицы _**B**_ (из Задания 9) и _**C**_ (из Задания 12) - в качестве источников данных, получите матрицу _**E**_ размером 4x4. Элементы матрицы _**E**_, для которых соответствующий элемент матрицы _**D_inv_new**_ равен 1, должны быть равны соответствующему элементу матрицы _**B**_, а элементы матрицы _**E**_, для которых соответствующий элемент матрицы _**D_inv_new**_ равен 0, должны быть равны соответствующему элементу матрицы _**C**_.

In [28]:
D_inv_new = np.where(D_inv < 0, 0, 1)
print('Матрица D_inv_new:\n', D_inv_new)
print('Тип матрицы D_inv_new: {}'.format(D_inv_new.dtype))
print('Форма матрицы D_inv_new: {}'.format(D_inv_new.shape))

Матрица D_inv_new:
 [[1 1 0 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 0 0 1]]
Тип матрицы D_inv_new: int32
Форма матрицы D_inv_new: (4, 4)


In [29]:
print('Матрица B:\n', B)
print('Тип матрицы B: {}'.format(B.dtype))
print('Форма матрицы B: {}'.format(B.shape))

Матрица B:
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Тип матрицы B: int32
Форма матрицы B: (4, 4)


In [30]:
print('Матрица C:\n', C)
print('Тип матрицы C: {}'.format(C.dtype))
print('Форма матрицы C: {}'.format(C.shape))

Матрица C:
 [[12 14 10  7]
 [12  4  6  9]
 [ 2  6 10 10]
 [ 7  4  3  7]]
Тип матрицы C: int32
Форма матрицы C: (4, 4)


In [31]:
E = np.where(D_inv_new > 0, B, C)
print('Матрица E:\n', E)
print('Тип матрицы E: {}'.format(E.dtype))
print('Форма матрицы E: {}'.format(E.shape))

Матрица E:
 [[  5  14  10   7]
 [ 14   4   6 122]
 [  2  86 149  10]
 [  7   4   3 302]]
Тип матрицы E: int32
Форма матрицы E: (4, 4)


------
END Части 2